(SIMP-8926) Bootstrap  needs absolute path
simp/pupmod-simp-simp pull request #247
Opened 2020-12-22 00:00 UTC by jeannegreulich

- changed a call to puppet in the bootstrap_simp_client to
  use absolute path to puppet command.

SIMP-8926 #close

2020-12-22 01:19 UTC, op-ct approved these changes

2021-01-04 13:56 UTC, lnemsick-simp requested changes
Couple of nits

2021-01-04 13:56 UTC, lnemsick-simp commented on files/var/www/ks/bootstrap_simp_client
> +    result = execute("/opt/puppetlabs/bin/puppet resource service #{service_name} enable=false")
* Please make `/opt/puppetlabs/bin/puppet` a class constant (e.g., `PUPPET`) or variable (e.g. `@puppet`)
* The `if File.exists?('/opt/puppetlabs/bin/puppet` logic on lines 18-22 no longer make sense if you are assuming a specific path for the puppet executable.  Please fix.

2021-01-08 19:05 UTC, lnemsick-simp commented
Unit tests are failing in code that was not modified by this PR.

2021-01-11 16:22 UTC, lnemsick-simp commented
I'll look into the acceptance tests failures.

2021-01-11 17:12 UTC, lnemsick-simp commented
The problem is that the `domain` fact returns nil.  /etc/resolv.conf does not have a `search` or `domain` entry in it and `hostname` does not return a fqdn.  So the `domain` fact returns nil.

NOTE:  This is the contents of /etc/resolv.conf:
# Generated by NetworkManager
nameserver 8.8.8.8
options attempts:2 ndots:1 rotate timeout:2

2021-01-22 14:55 UTC, lnemsick-simp approved these changes

2021-01-22 15:11 UTC, merged